<a href="https://colab.research.google.com/github/Yashwanth112004/Machine-Learning/blob/main/AmericanExpressDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#American Express Data Analysis

#Deep Learning via ANN





In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.17.0'

In [ ]:
data_set = pd.read_excel('/content/sample_data/AmericanExpressExitPredicton.xlsx')
### Dividing the data
X = data_set.iloc[:,0:-1].values
y = data_set.iloc[:,-1].values


In [ ]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [ ]:
print(y)

[0 0 0 ... 0 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X[3])

[0.0 1.0 0.0 428 1 51 3 0.0 4 1 86868]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

##ANN Initialization

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Input(shape=(11,)))

#Adding first Hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

#Adding Second Input Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

#Adding Output Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#ANN Compiling

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#ANN Training

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7974 - loss: 0.5896
Epoch 2/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7987 - loss: 0.4921
Epoch 3/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7960 - loss: 0.4627
Epoch 4/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7891 - loss: 0.4635
Epoch 5/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7910 - loss: 0.4521
Epoch 6/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7979 - loss: 0.4318
Epoch 7/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7959 - loss: 0.4335
Epoch 8/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7950 - loss: 0.4284
Epoch 9/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8000 - loss: 0.4199
Epoch 10/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7873 - loss: 0.4289
Epoch 11/100
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7972 - loss: 0.4154
Epoch 12/100
249/249 ━━━━━━━━━━━━━━━━━━━━

#Predictions

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


#Accuracy Check and Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   60]
 [ 233  180]]


0.8524672708962739

#User Input and Output

In [ ]:
def predict_exit(geography, credit_score, gender, age, Customer_since, Current_Account, num_of_products, UPI_enabled, estimated_salary):

  features = np.array([[credit_score, geography, gender, age, Customer_since, Current_Account, num_of_products, UPI_enabled, estimated_salary]])
  features[:, 2] = le.transform(features[:, 2])
  features = ct.transform(features)
  features = sc.transform(features)
  # Make prediction
  prediction = ann.predict(features) > 0.5
  # Print output
  print("Prediction: ", prediction)

geography = input("Geography : ")
credit_score = float(input("Credit Score: "))
gender = input("Gender (Male/Female): ")
age = float(input("Age: "))
Customer_since = float(input("Tenure: "))
Current_Account = float(input("Balance: "))
num_of_products = float(input("Number of Products: "))
UPI_enabled = float(input("Has UPI_enabled (0 for No, 1 for Yes): "))
estimated_salary = float(input("Estimated Salary: "))

predict_exit(geography, credit_score, gender, age, Customer_since, Current_Account, num_of_products, UPI_enabled, estimated_salary)

KeyboardInterrupt: Interrupted by user