#American Express Data Analysis

#Deep Learning via ANN





In [22]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [23]:
tf.__version__

'2.17.0'

In [24]:
data_set = pd.read_excel('/content/sample_data/AmericanExpressExitPredicton.xlsx')
### Dividing the data
X = data_set.iloc[:,0:-1].values
y = data_set.iloc[:,-1].values


In [25]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [26]:
print(y)

[0 0 0 ... 0 1 0]


In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [28]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [30]:
print(X[3])

[0.0 1.0 0.0 428 1 51 3 0.0 4 1 86868]


In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

##ANN Initialization

In [33]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Input(shape=(11,)))

#Adding first Hidden layer

In [34]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

#Adding Second Input Layer

In [35]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

#Adding Output Layer

In [36]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#ANN Compiling

In [37]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#ANN Training

In [38]:
ann.fit(X_train, y_train, batch_size=32, epochs=120)

Epoch 1/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5881 - loss: 0.6823
Epoch 2/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7903 - loss: 0.4897
Epoch 3/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7892 - loss: 0.4624
Epoch 4/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7929 - loss: 0.4579
Epoch 5/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7981 - loss: 0.4365
Epoch 6/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7988 - loss: 0.4348
Epoch 7/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7958 - loss: 0.4385
Epoch 8/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8088 - loss: 0.4246
Epoch 9/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8028 - loss: 0.4328
Epoch 10/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8068 - loss: 0.4289
Epoch 11/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8130 - loss: 0.4256
Epoch 12/120
249/249 ━━━━━━━━━━━━━━━━━━━━

#Predictions

In [39]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


#Accuracy Check and Confusion Matrix

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   60]
 [ 239  174]]


0.8494461228600202

#User Input and Output

In [41]:
def predict_exit(geography, credit_score, gender, age, Customer_since, Current_Account, num_of_products, UPI_enabled, estimated_salary):

  features = np.array([[credit_score, geography, gender, age, Customer_since, Current_Account, num_of_products, UPI_enabled, estimated_salary]])
  features[:, 2] = le.transform(features[:, 2])
  features = ct.transform(features)
  features = sc.transform(features)
  # Make prediction
  prediction = ann.predict(features) > 0.5
  # Print output
  print("Prediction: ", prediction)

geography = input("Geography : ")
credit_score = float(input("Credit Score: "))
gender = input("Gender (Male/Female): ")
age = float(input("Age: "))
Customer_since = float(input("Tenure: "))
Current_Account = float(input("Balance: "))
num_of_products = float(input("Number of Products: "))
UPI_enabled = float(input("Has UPI_enabled (0 for No, 1 for Yes): "))
estimated_salary = float(input("Estimated Salary: "))

predict_exit(geography, credit_score, gender, age, Customer_since, Current_Account, num_of_products, UPI_enabled, estimated_salary)

Geography : Mumbai
Credit Score: 554
Gender (Male/Female): Male
Age: 25
Tenure: 7
Balance: 196440
Number of Products: 4
Has UPI_enabled (0 for No, 1 for Yes): 1
Estimated Salary: 123456789
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
Prediction:  [[ True]]
